name: "Tests"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

    branches:
      - master
    tags:
      - ci
      - tests  
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md

  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md

env:
  PYTEST_ADDOPTS: "--color=yes"
  PYTHON_VERSION: 'pypy-3.9'
  TESTING_GITHUB_TOKEN: "{{ secrets.TESTING_GITHUB_TOKEN }}"

jobs:
  precommit:
    runs-on: ubuntu-latest
    container: ghcr.io/marshall7m/terrace:v0.1.0
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Hooks
        shell: bash
        run: |
          pre-commit install
          pre-commit run --all-files

  unit:
    needs: precommit
    runs-on: ubuntu-latest
    container: ghcr.io/marshall7m/terrace:v0.1.0
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: mask sensitive
        run: echo "::add-mask::$TESTING_GITHUB_TOKEN"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - name: Tests
        id: pytest
        shell: bash
        run: |
          source $VIRTUAL_ENV/bin/activate
          python3 -m pip install -e .

          pytest -vv tests/unit

  integration:
    needs: [precommit, unit]
    runs-on: ubuntu-latest
    container: ghcr.io/marshall7m/terrace:v0.1.0
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: mask sensitive
        run: echo "::add-mask::$TESTING_GITHUB_TOKEN"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - name: Tests
        id: pytest
        shell: bash
        run: |
          source $VIRTUAL_ENV/bin/activate
          python3 -m pip install -e .

          pytest -vv tests/integration